### PR TITLE
remove https from get site URLs

### PR DESCRIPTION
**Pull request by danielmurphy**

### CODE REVIEW

**Comment by bensie** [comment]
:+1: 

Why don't we serve the get site over HTTPS? I think it might be a quick Heroku add-on.

**Comment by TheBerg** [comment]
:+1:

**Comment by danielmurphy** [comment]
I'd rather add SSL to the get site for sure. Can we do that @TheBerg? @justicel?

**Comment by TheBerg** [comment]
@danielmurphy Jeff Berg is on vacation, sorry.

**Comment by bensie** [comment]
@danielmurphy You'll need to get the SSL cert and private key from @justicel (maybe we get a new one signed just for the get site so our main private key isn't in Heroku's hands). Then just need an app owner account to get the add-on installed: https://addons.heroku.com/ssl.

**Comment by danielmurphy** [comment]
I'm merging this until Jeff gets back since we need the owner to add SSL to the get site.

**Pull request merged**
